[build]
  base = "client/"
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://web-production-3d986.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
